apiVersion: v1
kind: Service
metadata:
  name: pulseurl-go-example
  labels:
    app: pulseurl-go-example
spec:
  type: ClusterIP
  ports:
  - name: http
    port: ${HTTP_PORT}
    targetPort: http
    protocol: TCP
  selector:
    app: pulseurl-go-example
