// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/traffic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrafficEvent represents a single HTTP/gRPC traffic event
type TrafficEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	PodId         string                 `protobuf:"bytes,3,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Route         string                 `protobuf:"bytes,6,opt,name=route,proto3" json:"route,omitempty"`
	HttpMethod    string                 `protobuf:"bytes,7,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	StatusCode    int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	DurationMs    int32                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ClientIp      string                 `protobuf:"bytes,10,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CustomLabels  map[string]string      `protobuf:"bytes,12,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficEvent) Reset() {
	*x = TrafficEvent{}
	mi := &file_proto_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficEvent) ProtoMessage() {}

func (x *TrafficEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficEvent.ProtoReflect.Descriptor instead.
func (*TrafficEvent) Descriptor() ([]byte, []int) {
	return file_proto_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TrafficEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TrafficEvent) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *TrafficEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TrafficEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TrafficEvent) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *TrafficEvent) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *TrafficEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TrafficEvent) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TrafficEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *TrafficEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *TrafficEvent) GetCustomLabels() map[string]string {
	if x != nil {
		return x.CustomLabels
	}
	return nil
}

// Ack is the acknowledgment response
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_traffic_proto protoreflect.FileDescriptor

const file_proto_traffic_proto_rawDesc = "" +
	"\n" +
	"\x13proto/traffic.proto\x12\bpulseurl\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x03\n" +
	"\fTrafficEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x15\n" +
	"\x06pod_id\x18\x03 \x01(\tR\x05podId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x14\n" +
	"\x05route\x18\x06 \x01(\tR\x05route\x12\x1f\n" +
	"\vhttp_method\x18\a \x01(\tR\n" +
	"httpMethod\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x05R\n" +
	"durationMs\x12\x1b\n" +
	"\tclient_ip\x18\n" +
	" \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12M\n" +
	"\rcustom_labels\x18\f \x03(\v2(.pulseurl.TrafficEvent.CustomLabelsEntryR\fcustomLabels\x1a?\n" +
	"\x11CustomLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2|\n" +
	"\rTrafficLogger\x121\n" +
	"\bLogEvent\x12\x16.pulseurl.TrafficEvent\x1a\r.pulseurl.Ack\x128\n" +
	"\rLogEventBatch\x12\x16.pulseurl.TrafficEvent\x1a\r.pulseurl.Ack(\x01B'Z%github.com/pulseurl/pulseurl-go/protob\x06proto3"

var (
	file_proto_traffic_proto_rawDescOnce sync.Once
	file_proto_traffic_proto_rawDescData []byte
)

func file_proto_traffic_proto_rawDescGZIP() []byte {
	file_proto_traffic_proto_rawDescOnce.Do(func() {
		file_proto_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_traffic_proto_rawDesc), len(file_proto_traffic_proto_rawDesc)))
	})
	return file_proto_traffic_proto_rawDescData
}

var file_proto_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_traffic_proto_goTypes = []any{
	(*TrafficEvent)(nil),          // 0: pulseurl.TrafficEvent
	(*Ack)(nil),                   // 1: pulseurl.Ack
	nil,                           // 2: pulseurl.TrafficEvent.CustomLabelsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_traffic_proto_depIdxs = []int32{
	3, // 0: pulseurl.TrafficEvent.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: pulseurl.TrafficEvent.custom_labels:type_name -> pulseurl.TrafficEvent.CustomLabelsEntry
	0, // 2: pulseurl.TrafficLogger.LogEvent:input_type -> pulseurl.TrafficEvent
	0, // 3: pulseurl.TrafficLogger.LogEventBatch:input_type -> pulseurl.TrafficEvent
	1, // 4: pulseurl.TrafficLogger.LogEvent:output_type -> pulseurl.Ack
	1, // 5: pulseurl.TrafficLogger.LogEventBatch:output_type -> pulseurl.Ack
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_traffic_proto_init() }
func file_proto_traffic_proto_init() {
	if File_proto_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_traffic_proto_rawDesc), len(file_proto_traffic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_traffic_proto_goTypes,
		DependencyIndexes: file_proto_traffic_proto_depIdxs,
		MessageInfos:      file_proto_traffic_proto_msgTypes,
	}.Build()
	File_proto_traffic_proto = out.File
	file_proto_traffic_proto_goTypes = nil
	file_proto_traffic_proto_depIdxs = nil
}
