// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/traffic.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficLogger_LogEvent_FullMethodName      = "/pulseurl.TrafficLogger/LogEvent"
	TrafficLogger_LogEventBatch_FullMethodName = "/pulseurl.TrafficLogger/LogEventBatch"
)

// TrafficLoggerClient is the client API for TrafficLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TrafficLogger service for logging traffic events
type TrafficLoggerClient interface {
	// LogEvent logs a single traffic event
	LogEvent(ctx context.Context, in *TrafficEvent, opts ...grpc.CallOption) (*Ack, error)
	// LogEventBatch logs multiple events in a stream (for future use)
	LogEventBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TrafficEvent, Ack], error)
}

type trafficLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficLoggerClient(cc grpc.ClientConnInterface) TrafficLoggerClient {
	return &trafficLoggerClient{cc}
}

func (c *trafficLoggerClient) LogEvent(ctx context.Context, in *TrafficEvent, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TrafficLogger_LogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficLoggerClient) LogEventBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TrafficEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrafficLogger_ServiceDesc.Streams[0], TrafficLogger_LogEventBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrafficEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficLogger_LogEventBatchClient = grpc.ClientStreamingClient[TrafficEvent, Ack]

// TrafficLoggerServer is the server API for TrafficLogger service.
// All implementations must embed UnimplementedTrafficLoggerServer
// for forward compatibility.
//
// TrafficLogger service for logging traffic events
type TrafficLoggerServer interface {
	// LogEvent logs a single traffic event
	LogEvent(context.Context, *TrafficEvent) (*Ack, error)
	// LogEventBatch logs multiple events in a stream (for future use)
	LogEventBatch(grpc.ClientStreamingServer[TrafficEvent, Ack]) error
	mustEmbedUnimplementedTrafficLoggerServer()
}

// UnimplementedTrafficLoggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficLoggerServer struct{}

func (UnimplementedTrafficLoggerServer) LogEvent(context.Context, *TrafficEvent) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogEvent not implemented")
}
func (UnimplementedTrafficLoggerServer) LogEventBatch(grpc.ClientStreamingServer[TrafficEvent, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method LogEventBatch not implemented")
}
func (UnimplementedTrafficLoggerServer) mustEmbedUnimplementedTrafficLoggerServer() {}
func (UnimplementedTrafficLoggerServer) testEmbeddedByValue()                       {}

// UnsafeTrafficLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficLoggerServer will
// result in compilation errors.
type UnsafeTrafficLoggerServer interface {
	mustEmbedUnimplementedTrafficLoggerServer()
}

func RegisterTrafficLoggerServer(s grpc.ServiceRegistrar, srv TrafficLoggerServer) {
	// If the following call pancis, it indicates UnimplementedTrafficLoggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficLogger_ServiceDesc, srv)
}

func _TrafficLogger_LogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficLoggerServer).LogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficLogger_LogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficLoggerServer).LogEvent(ctx, req.(*TrafficEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficLogger_LogEventBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficLoggerServer).LogEventBatch(&grpc.GenericServerStream[TrafficEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficLogger_LogEventBatchServer = grpc.ClientStreamingServer[TrafficEvent, Ack]

// TrafficLogger_ServiceDesc is the grpc.ServiceDesc for TrafficLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulseurl.TrafficLogger",
	HandlerType: (*TrafficLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogEvent",
			Handler:    _TrafficLogger_LogEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LogEventBatch",
			Handler:       _TrafficLogger_LogEventBatch_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/traffic.proto",
}
